// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyzhyKO9VkifF7xJqqzuaas0doAY687Xo',
    appId: '1:669397400120:web:3e7bba47939ed6577c84cd',
    messagingSenderId: '669397400120',
    projectId: 'test-790b2',
    authDomain: 'test-790b2.firebaseapp.com',
    storageBucket: 'test-790b2.appspot.com',
    measurementId: 'G-LTP2BV2Z14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzOE__TwBgyvqZDCCGScRai1y7sddH_H4',
    appId: '1:669397400120:android:b314052ccbfd4cd37c84cd',
    messagingSenderId: '669397400120',
    projectId: 'test-790b2',
    storageBucket: 'test-790b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rSYRvlsp6oYIJCWnxg74slpWmGngu-U',
    appId: '1:669397400120:ios:51ecd5ad07b892647c84cd',
    messagingSenderId: '669397400120',
    projectId: 'test-790b2',
    storageBucket: 'test-790b2.appspot.com',
    iosClientId:
        '669397400120-fr0vvcpr36rd1a1cshdvsjr37nujpmmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
